### ISSUE TITLE
List on Artifacthub

### ISSUE THREAD

**Issue by bornav** [openzipkin/zipkin-helm#21]
Not sure what is the process of listing a chart on the Artifacthub, but having the chart listed there could help in discoverability, and ease of configuration

**Comment by codefromthecrypt** [comment]
good idea. can you help with this? what's the process?

**Comment by bornav** [comment]
> good idea. can you help with this? what's the process?

Will take a look

**Comment by codefromthecrypt** [comment]
@reta mind claiming on this one on behalf of us per instructions?

**Comment by bornav** [comment]
Closing as there I snow an official chart available, Thanks

**Comment by bornav** [comment]
Missed the comment from @reta

**Comment by reta** [comment]
@bornav thanks for checking, it seems like the repository URL is `https://zipkin.io/zipkin-helm/` but there is nothing behind this URL at the moment, fixing this next
